config/routes.rb
Rails.application.routes.draw do
  
  post 'users/upvote/:id' => 'users#upvote' , as: 'upvote_answer'
  
  root 'users#root'
  
  get '/questions/search' => 'questions#search' , as: 'search_question'

  devise_for :users
  resources :questions do 
    member do
      post 'answer'
    end
    collection do
      
    end
  end
  get 'users/:id' => 'users#profile' , as: 'user_profile'
  get 'users/:id/ques' => 'users#sudo_profile' , as: 'user_sudoprofile'

  patch 'users/:id/edit' => 'users#save_profile'
  patch 'users/follow' => 'users#follow', as: 'users_follow'

  
  get "*path" => redirect('/')

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :user
	belongs_to :question
	has_and_belongs_to_many :upvotees, class_name: "User"
	validates_presence_of :text, :question_id
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :answers
	validates_presence_of :text , :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
 	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
	mount_uploader :avatar, AvatarUploader
	has_many :questions
	has_many :answers #For the answers of particular user
	has_and_belongs_to_many :voted_answers, class_name: "Answer" #For the answers upvoted by particular user
	has_and_belongs_to_many :followers, class_name: 'User', :join_table => "followees_followers", foreign_key: "followee_id", association_foreign_key: "follower_id"
	has_and_belongs_to_many :followees, class_name: 'User', :join_table => "followees_followers", foreign_key: "follower_id", association_foreign_key: "followee_id"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  add_flash_types :pop
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_user

  def after_sign_in_path_for(resource)
    '/questions'
  end

   def user_image_url(user)
    # byebug
    if @user.avatar.url.nil?
      "thumb_default_pic.jpg"
    else
      @user.avatar.url(:thumb)
    end
  end


  def user_voted answer
    u = current_user.voted_answers.find_by_id(answer.id)
    if u.nil?
      return false
    else
      return true
    end
  end
  
  helper_method :user_voted

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name , :number])
  end

  def set_user
  	if user_signed_in?
  		@user = current_user
  	else
  		@user = User.new()
  	end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :answer]
  before_action :authenticate_user!, only: [:answer, :new, :create, :update, :destroy]
  # GET /questions
  # GET /questions.json
  def index
    @users=User.all
    @questions = Question.order("updated_at DESC").all
  end

  def answer
    ans = Answer.new(answer_params)
    ans.question_id = @question.id
    ans.user_id = current_user.id
    ans.save
    redirect_to @question
  end

  def search
    query = params[:query]
    @questions = Question.where("text like '%#{query}%'")
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answer = Answer.new
    @user= current_user
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    respond_to do |format|
      if @question.save
        format.html { redirect_to '/', notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:text)
    end

    def answer_params
      params.require(:answer).permit(:text)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:upvote, :edit_profile, :follow]
  def profile
    @user = User.find_by_id(params[:id])
    if @user.nil?
      redirect_to root_path
    end
  end

  def sudo_profile
    @user = User.find_by_id(params[:id])
    if @user.nil?
      redirect_to root_path
    end
  end

  def root
    render :layout => 'root'
  end

  def upvote
    u = current_user
    a = Answer.find(params[:id])
    if user_voted a
      a.upvotees.delete(u)
      a.votes= a.votes-1
      a.save
    else
      a.upvotees << u
      a.votes= a.votes+1
      a.save
    end
    redirect_to a.question
  end

  def questions_asked user
    Question.where(user_id: user.id)
  end

  def answers_given user
    Answer.where(user_id: user.id)
  end

  def save_profile
    user = User.find(params[:user][:id])
    user.name = params[:user][:name]
    user.number = params[:user][:number]
    user.description = params[:user][:description]
    if(not params[:user][:avatar].nil?)
      user.avatar = params[:user][:avatar]
    end
    user.save
    redirect_to user_profile_path(user.id)
  end

 

  def follow
    u = User.find_by_id(params[:profile_id])
    if(not u.nil?)
      if(user_following u)
          current_user.followees.delete(u)
      else
          current_user.followees << u
      end
      current_user.save
      redirect_to user_profile_path(u)
      return
    end
    redirect_to root_path
  end

  def user_following user
    if(user.followers.find_by_id(current_user.id).nil?)
      false
    else
      true
    end
  end
  helper_method :questions_asked, :answers_given , :user_image_url , :user_following

end

app/helpers/application_helper.rb
module ApplicationHelper

	def user_image_url(user)
    # byebug
    if user.avatar.url.nil?
      "thumb_default_pic.jpg"
    else
      user.avatar.url(:thumb)
    end

end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QandA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
          
</head>
<body>

<% if not notice.nil? or not alert.nil? %>
    <div id="alert"><p id="notice" style="color :#a16e4b ;  "  ><%=notice %></p>
      <p id="alert" style=" color : #a16e4b ; "><%=alert %></p>
    </div>
<% end %>

<div class="navbar">
  <nav>
    <div class="nav-wrapper" style="margin: 0px 90px 0px 90px;">
      <a href="/questions" class="brand-logo">QandA</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="fa fa-list-ul" aria-hidden="true" style="font-size: 35px;"></i></a>
      <ul id="head_nav" class="right hide-on-med-and-down">
        <li><a href="/questions/new">Ask <i class="fa fa-question" aria-hidden="true""></i></a></li>
        <% if user_signed_in? %>
            <li>
              <div class='dropdown-button btn' data-activates='dropdown1' style="max-width : 180px;">Hi <%=current_user.name %></div>
              <!-- Dropdown Structure -->
              <ul id='dropdown1' class='dropdown-content'>
                <li><%= link_to "Profile", user_profile_path(current_user.id)%></li>
                <li class="divider"></li>
                <li><%= link_to "SignOut", destroy_user_session_path, method: "Delete"%></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "LogIn", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end%>
        </li>
        <!--<li>
          <nav>
            <div class="nav-wrapper">
              <form action="/questions/search" method="get">
                <div class="input-field">
                  <input id="search" name="query" type="search" required>
                  <label for="search"><i class="material-icons">search</i></label>
                  <i class="material-icons">close</i>
                </div>
              </form>
            </div>
          </nav>
        </li>
      </ul>-->
      <ul class="side-nav" id="mobile-demo">
        <li><a href="/questions/new"">Ask Question</a></li>
        <% if user_signed_in? %>
            <li style="color: black;">
              <%= link_to "Hello "+current_user.name, '#'%>
            </li>
            <li style="color: black;">
              <%= link_to "Profile", user_profile_path(current_user.id)%>
            </li>
            <li>
              <%= link_to "SignOut", destroy_user_session_path, method: "Delete"%>
            </li>
        <% else %>
            <li>
              <%= link_to "LogIn", new_user_session_path %>
            </li>
            <li>
              <%= link_to "Sign Up", new_user_registration_path %>
            </li>
        <% end %>
        <li>
          <nav>
            <div class="nav-wrapper">
              <form action="/questions/search" method="get">
                <div class="input-field">
                  <input id="search" name="query" type="search" required>
                  <label for="search"><i class="material-icons">search</i></label>
                  <i class="material-icons">close</i>
                </div>
              </form>
            </div>
          </nav>
        </li>
      </ul>
    </div>
  </nav>
</div>


<div style="padding-top: 50px; padding-bottom: 120px;">
  <%= yield %>
</div>

 <footer class="page-footer" style="margin-bottom: 0;">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">About Us</h5>
                <p class="grey-text text-lighten-4">We are a team of college students working on this project.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Developed By</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="https://www.facebook.com/apoorva.smartgirl">Apoorva Sharma</a></li>
                  <li><a class="grey-text text-lighten-3" href="https://www.facebook.com/apurvavrupa">Apurva Singh</a></li>
                  <li><a class="grey-text text-lighten-3" href="https://www.facebook.com/IshaShiwach">Isha</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2017 Quora
            </div>
          </div>
</footer>

<script>
  $(document).ready(function(){
    $(".button-collapse").sideNav();
    $("#alert").delay(4000).slideUp('slow');
    $('.dropdown-button').dropdown({
      inDuration: 400,
      outDuration: 600,
      constrain_width: true, // Does not change width of dropdown to that of the activator
      hover: true, // Activate on hover
      gutter: 0, // Spacing from edge
      belowOrigin: true, // Displays dropdown below the button
      alignment: 'left' // Displays dropdown with edge aligned to the left of button
        }
    );
    })
  <% if not pop.nil? %>
  alert("<%= pop %>")
  <%end%>
</script>

</body>
</html>

app/views/layouts/root.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QandA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
          
</head>
<body>
<%= yield %>
</body>
</html>

app/views/questions/_answer.html.erb
 <div class="answer-card">
 	
 	<div id="v">
 		<%= image_tag user_image_url(answer.user),class: "avatar pic circle"%>
 		<p><%=answer.user.name%><br>Uploaded on <%=answer.user.created_at%></p>
 	</div>
 	<div>
 		<p style="font-size: 20px;"><%= answer.text%></p>
 	</div>
 	<div>
 		<div>
 			<% if user_signed_in? %>
 				<%= form_for(@answer, :url => "/users/upvote/#{answer.id}" )do|f|%>
 					<% if user_voted(answer) %>
  						<div class="waves-effect waves-light btn action">
  						<i class="material-icons left">thumb_down</i><%= f.submit "Downvote" %>| <%=answer.votes%>
  						</div>
  					<%else%> 
  						<div class="waves-effect waves-light btn action">
  						<i class="material-icons left">thumb_up</i><%= f.submit "Upvote" %>| <%=answer.votes%>
  						</div>
  					<%end%>
 				<%end%>
 			<%end%>
 			
 		</div>
	</div>
 </div>


 

app/views/questions/_form.html.erb
<div class="card-panel z-depth-3" style="background-color:#efebe9 ;">
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
  <div class="input-field col s12 field">
    <%= f.label :question_text %><br>
    <%= f.text_field :text, required: true %>
  </div>
  </div>
  <div class="modal-footer"> 
  <div class="modal-action modal-close waves-effect waves-green btn-flat">
    <%= f.submit %>
  </div>
  </div>
<% end %>
</div>

app/views/questions/_question.html.erb
<div class="card z-depth-3">
	<div class="card-content brown darken-1">
       <span class="card-title"><%= link_to "Q: "+question.text, question, id: "ques" %></span>
    </div>
    <div class="card-action text">
       <i class="tiny material-icons">mode_edit</i><%= question.user.name %>
       <span style="display:inline-block; width: 20px;"></span>
       <i class="fa fa-comment-o" aria-hidden="true"></i>&nbsp;<%= question.answers.count %>
    </div>
</div>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div id="root">

<div id="side">	
    <p style="color:#5d4037; font-size: 25px;">Feeds:</p>
</div>

<div id="first">
<% @questions.each do |question| %>
    <%= render 'question', :question => question %> 
<% end %>
</div>

<div id="vertical_line">	
</div>

<div id="second">
<ul class="collection">
	<% @users.each do |user| %>
	<% if user != current_user %>
    <li class="collection-item avatar">
    <%= link_to user_profile_path(user.id) do %>
    <%= image_tag user_image_url(user),class: "avatar circle"%>
    <% end %> 
    <strong><span><%= link_to  user.name, user_profile_path(user.id),class: "title user"  %></span></strong>
    <p style="color:#5d4037"><%= user.description %></p>
    </li>
    <% end %>
    <% end %>
  </ul>
</div>

</div>

app/views/questions/new.html.erb
<div class="container">
<div class="card-panel z-depth-3 " style="background-color:#efebe9;">
<%= render 'form' %>
<br/>
<%= link_to 'Back', questions_path, class: "btn waves-effect waves-light"%>
</div>
</div>

app/views/questions/search.html.erb
<div>
<% if @questions.count==0 %>
	<h1> No matches found!! </h1>
<% else %>
	<h1>
		Related searched are :
	</h1>
	<% @questions.each do |question| %>
	    <%= render 'question', :question => question %> 
	<% end %>
<% end %>
</div>

app/views/questions/show.html.erb
<div class="container">

	<div class="card-content white">
       <span class="card-title" data-confirm="are you sure?" style="color: brown; font-size: 50px; font-weight:400;"><%= @question.text%></span>
       <div id="answer">
       <section id="section" class="show">
        <a href="#section"class="waves-effect waves-light btn" style="font-size: 20px; padding-bottom: 40px;"><i class="medium material-icons">mode_edit</i>ANSWER</a>
        <div>
            <div class="card z-depth-3" style="background-color:#efebe9 ;">
            <div class="card-content brown lighten-2">
            <span class="card-title" style="height: 100px; display: flex;align-items: center;">
            <div style="padding-right: 20px;"><%= image_tag user_image_url(@user),class: "avatar circle"%></div>
            <div><p style="color: white; font-size: 30px;">As: <%=@user.name%></p></div>
            </span>
            </div>
            <div class="card-action text">
            <%=form_for(@answer, :url => answer_question_path(@question)) do|f|%>
           <div class="row">
           <div class="input-field col s12 field">
                <%= f.label :answer %><br>
                <%= f.text_field :text, required: true %>
            </div>
            </div>
            <div class="btn waves-effect waves-light action">
              <%= f.submit %>
            </div>
              <%end%>
              </div>
              </div>
        </div>
       </section>
  </div>
  </div>

  <div id="ans_count">
  <% if @question.answers.count==1 %>
      1 Answer
      <% else %>
        <%= @question.answers.count%> Answers
  <% end %>
  </div>
  <div id="horizontal_line"></div>

<% @question.answers.order("votes ASC").each() do|answer|%>
	<%=render 'answer', :answer => answer%>
  <div id="horizontal_line"></div>
<%end%>


</div>

app/views/users/_answers.html.erb
<div class="card z-depth-3" style="height: 200px;margin-bottom: 20px;">
	<div class="card-content brown darken-1">
       <span class="card-title"><%= link_to Question.find_by_id(answer.question_id).text, question_path(Question.find_by_id(answer.question_id)),class: "color" %></span>
     </div>
    <div class="card-action text">
        	<div style="display:flex;align-items:center;"><%= image_tag user_image_url(answer.user),class: "avatar pic circle"%>
 		<p style="margin-left: 20px;"><%=answer.user.name%><br>Uploaded on <%=answer.user.created_at%></p>
 		</div>
 	</div>
</div>
 

app/views/users/_form.html.erb
<%= form_for(@user, url: "/users/#{@user.id}/edit") do |f| %>
    <div class="row">
    <div class="input-field col s6">
    <p>
      <%= f.label "Name" %>
      <%= f.text_field :name %>
    </p>
    </div>
    <div class="input-field col s6">
    <p>
      <%= f.label "Contact Number" %>
      <%= f.text_field :number %>
    </p>
    </div>
    </div>

    <div class = "row">
    <div class="iput-field col s12">
    <p>
      <%= f.label "description" %>
    <%= f.text_field :description %>
    </p>
    </div>      
    </div>

    <p>
      <%= f.hidden_field :id %>
    </p>
    <div class="file-field input-field">
      <div class="btn">
        <span>File</span>
        <%= f.file_field :avatar%>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>

    <p class="btn waves-effect waves-light"><%= f.submit "Update Profile"%></p>

<% end %>

app/views/users/_questions.html.erb
<div class="card z-depth-3">
	<div class="card-content brown darken-1">
       <span class="card-title"><%= link_to "Q: "+question.text, question, id: "ques" %></span>
    </div>
    <div class="card-action text">
       <i class="tiny material-icons">mode_edit</i><%= question.user.name %>
       <span style="display:inline-block; width: 20px;"></span>
       <i class="fa fa-comment-o" aria-hidden="true"></i>&nbsp;<%= question.answers.count %>
    </div>
</div>

app/views/users/profile.html.erb
<div id="pic_edit">
<div id="profile_pic">
    <%= image_tag user_image_url(@user),class: "avatar"%>
</div>
<div id="name">
    <span><%= @user.name %></span>
    <div>
    <div class="chip" style="background-color:  #3e2723;">
        <p style="color:white;"> Following: <%=@user.followees.count%> </p>
    </div>
    <div class="chip" style="background-color:  #3e2723;">
        <p style="color:white;">Followers : <%=@user.followers.count%></p>
    </div>
    <a href="#modal1" class="waves-effect waves-light btn-floating btn-medium brown darken-4"><i class="material-icons">mode_edit</i></a>
    </div>
</div>
</div>




<div class="container" style="margin-top: 100px;">

<div class="row">
        <div class="col s6 m6">
          <div class="card brown darken-2" style="height: 250px;">
            <div class="card-content white-text">
              <span class="card-title">Description</span>
              <div style="background-color:white;height:1px;margin-bottom: 5px;"></div>
              <div id="card_text">
              <% if @user.description == "" || @user.description.nil? %>
                  <div id="description"><i class="tiny material-icons">mode_edit</i>
                  <p>ADD DESCRIPTION</p></div>
              <% else %>
                  <p><%=@user.description%></p>
              <% end %>
              </div>
            </div>
          </div>
        </div>

        <div class="col s6 m6">
          <div class="card brown darken-2" style="height: 250px;">
            <div class="card-content white-text" style="display:flex; flex-direction:column; align-items:center;">
              <div style="display: flex;">
              <span class="card-title">Questions : <%=questions_asked(@user).count%></span>&nbsp;&nbsp;<span class="card-title">Answers : <%=answers_given(@user).count%></span>
              </div>
              <div style="background-color:white;height:1px;margin-bottom: 5px;"></div>
              <div style="background-color:white;height:1px;margin-bottom: 5px;"></div>
              <div>
                  <% if user_signed_in? &&  @user.id != current_user.id %>
                      <%= form_for(@user, :url => "/users/follow" )do|f|%>
                          <%=  hidden_field_tag 'profile_id', @user.id %>
                          <% if user_following @user %>
                              <%= f.submit "Unfollow" %>
                          <%else%>
                              <%= f.submit "Follow" %>
                          <%end%>
                      <%end%>
                   <%end%>
              </div>
            </div>
          </div>
        </div>
</div>


</div>

<a href="#modal1">Edit Profile</a>

<div id="modal1" class="modal">
  <div class="modal-content">
    <%= render 'form' %>
  </div>
</div>

<script>
   $(document).ready(function(){
    $('.modal').modal();

  })
</script>

app/views/users/root.html.erb
<body id="indeximage">
<div id="root1">

<div class="row" >
        <div class="col s12 m6" >
          <div class="card brown darken-3"  id="sidelinks" >
          <div class="card-content white-text">
            <span class="card-title" id ="title">QandA</span>
            <p style="font-size: 17px;text-align:center;margin-top:20px;">(A place to share knowledge and better understand the world.)</p>
            <div id="linkswrap">
                <div id="sleek">
                   <p style="margin-top: 50px;">Confused? Ask the world! Get all your querries answered from people worldwide.</p>
                </div>
                <div id="verti">
                </div>
                <div  id="links">
                    <%= link_to "LogIn", new_user_session_path,class: "login"%>
                    <p style="font-size: 40px;">OR</p>
                    <%= link_to "Sign Up", new_user_registration_path, class: "signup"%>
                </div>
            </div>
          </div>
        </div>
      </div>

</div>


</body>

app/views/users/sudo_profile.html.erb
<div class="containerx">
<div id="pic_edit">
<div id="profile_pic">
    <%= image_tag user_image_url(@user),class: "avatar"%>
</div>
<div id="name">
    <span><%= @user.name %></span>
    <% if @user.description == "" || @user.description.nil? %>
    <% else %>
          <p>(<%=@user.description%>)</p>
    <% end %>
    <div>
    <div class="chip" style="background-color:  #3e2723;">
        <p style="color:white;"> Following: <%=@user.followees.count%> </p>
    </div>
    <div class="chip" style="background-color:  #3e2723;">
        <p style="color:white;">Followers : <%=@user.followers.count%></p>
    </div>
    <%if user_signed_in? && @user.id == current_user.id %>
    <a href="#modal1" class="waves-effect waves-light btn-floating btn-medium brown darken-4"><i class="material-icons">mode_edit</i></a>
    <% end %>
    </div>
    <div id="following">
    <% if user_signed_in? &&  @user.id != current_user.id %>
      <%= form_for(@user, :url => "/users/follow" )do|f|%>
        <%=  hidden_field_tag 'profile_id', @user.id %>
         <% if user_following @user %>
            <div class="waves-effect waves-light btn action" style="background-color:  #3e2723;">
            <%= f.submit "Unfollow" %>
            </div>
         <%else%>
            <div class="waves-effect waves-light btn action" style="background-color:  #3e2723;">
              <%= f.submit "Follow" %>
             </div>
         <%end%>
        <%end%>
    <%end%>
    </div>
     </div>
</div>



<div id="horizontal_line"></div>

<div id="quesans">

<div id="side_links"><ul>
<li><a href="/users/<%=@user.id%>">Answers : <%=answers_given(@user).count%></a></li>
<li><a href="/users/<%=@user.id%>/ques">Questions : <%=questions_asked(@user).count%></a></li>
</ul></div>

<div id="target2">
      <section id="userques">
        <% questions_asked(@user).each do |question|%>
          <%= render 'questions', :question => question %> 
          <div id="horizontal_line"></div>
        <% end %>
      </section>
</div>

</div>

<div id="modal1" class="modal">
  <div class="modal-content">
    <%= render 'form' %>
  </div>
</div>
</div>

<script>
   $(document).ready(function(){
    $('.modal').modal();

  })
</script>


    